import type { MetadataRoute } from 'next';

/**
 * PWA web-app manifest (served at /manifest.webmanifest by Next). Caregiving happens on a phone:
 * this makes Kintwadi installable to the home screen — full-screen, branded, one tap from the
 * pocket to "did Dad take his pills?". Icons are generated by scripts/generate-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Kintwadi — Coordinate Care Together',
    short_name: 'Kintwadi',
    description:
      'One shared record for everyone caring for someone — meds, timeline, appointments, tasks and a daily AI digest, across cities and countries.',
    id: '/',
    start_url: '/dashboard',
    display: 'standalone',
    background_color: '#FBFAF8',
    theme_color: '#0F766E',
    orientation: 'portrait-primary',
    categories: ['health', 'medical', 'lifestyle'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
